
<h2 class="page-header">in the moment</h2>


<div class="page-hero">


  <div id="mydog" class="video-poster">
    <img src="../img/poster-mydog.jpg" alt="Liska, My Dog"/>
  </div>

  <div class="video-description">

    <p class="title">
      
    </p>
    <p class="director">
      
    </p>
    <p class="body-copy">
      Bring it on the road. Bring it to the park. Bring it to the streets. Bring it everywhere you breathe. Because moments wait for no one and you never know when inspiration will strike.
      <br><br>
      Check out these incredible Canon-shot photographs and Full HD videos and then show us how you #bringit.
    </p>
    <!--<a id="mydog-cta" href="#" class="cta">How linda shot her film</a>-->

  </div>

 


</div>

 <div id="moment" class="page-hero-screens">
    <div>
      <img data="1" src="../img/mydog-still-1.jpg"/>
    </div>
    <div class="center-screen">
      <img data="2" src="../img/mydog-still-2.jpg"/>
    </div>
    <div>
        <img data="3" src="../img/mydog-still-3.jpg"/>
    </div>
  </div>




<div class="section-dividers">
  <p class="hashtag">#BRINGIT showcase</p>
</div>


<div id="moment" class="showcase">

 

  <div class="img-gallery">
    <div class ="carousel-cover"></div>
    
    <div id="img-1" class="mages">

      <div class="description">
            <br/>
            <p class="title">
              TIME FOR T at Optimus Alive, Lisbon. July 2013.
            </p>
            <p class="photographer">
             Ty Snaden
            </p>


            <p class="sub-heads">
               <!--Description-->
            </p>
            <p class="description-copy">
              This shot was very spontaneous. I was crossing the stage and I saw this musician from Time For T, so I quickly focused and took the shot. At music festivals, you need to be spontaneous. I didn’t use any special techniques, just the available light from outside the covered festival stage.  
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
              Canon EOS 5D DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF 50mm f/1.4 USM
            </p>

      </div>

      <img data="4" class="showcase-image" src="../img/showcase-moment-1.jpg" />

    </div>

    <div id="img-2" class="mages">

      <div class="description">
            <br/>
            <p class="title">
              Impromptu Jam Session at the Firehouse
            </p>
            <p class="photographer">
              David Tribby
            </p>


            <p class="sub-heads">
               <!--Description-->
            </p>
            <p class="description-copy">
              My close friend is an aspiring musician. One day, he was walking to a performance. Passing a firehouse, one of the firemen noticed Matt’s guitar and struck up a conversation. A couple minutes later he was free-styling guitar for a couple guys sitting in front of the fire truck. To get this shot, I only used natural light. 
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
              Canon EOS Rebel T2i DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF 24-70mm f/2.8L II USM
            </p>

      </div>

      <img data="5" class="showcase-image" src="../img/showcase-moment-2.jpg" />
      
    </div>

    <div id="img-3" class="mages">


      <div class="description">
            <br/>
            <p class="title">
              When a dream becomes a photograph
            </p>
            <p class="photographer">
              Celso Pereira Jr.
            </p>


            <p class="sub-heads">
               <!--Description-->
            </p>
            <p class="description-copy">
              I waited for the sun to set just enough where I could still get ambient light to illuminate the subject, but not from an obvious light source or direction. I pushed the limits of the camera sensor and lens aperture to give me depth of field without sacrificing shadow details, which were important for the feeling of "wondering into dreamland."
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
              Canon EOS 5D Mark II DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF 24-105mm f/4L IS USM
            </p>

      </div>

      <img data="6" class="showcase-image" src="../img/showcase-moment-3.jpg" />
      
    </div>

    <div id="img-4" class="mages">


      <div class="description">
            <br/>
            <p class="title">
              NO FEAR!
            </p>
            <p class="photographer">
              Lynne Gilbert
            </p>


            <p class="sub-heads">
               <!--Description-->
            </p>
            <p class="description-copy">
              When shooting waves, I always use the sports/action mode. It’s a phenomenal tool that I feel a lot of people don’t utilize nearly enough to get quick action shots. It was peak high tide and the waves were pounding and coming in hard. I captured a great series with the sports setting. Had I not used it I don’t think I would have captured half of the images I did, including this one.
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
              Canon EOS 60D DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF-S 18-55mm f/3.5-5.6 IS II
            </p>

      </div>

      <img data="7" class="showcase-image" src="../img/showcase-moment-4.jpg" />
      
    </div>

    <div id="img-5" class="mages">


      <div class="description">
            <br/>
            <p class="title">
              Why I Ride 
            </p>
            <p class="photographer">
              Daniel Schulze-Ardey 
            </p>


            <p class="sub-heads">
               <!--Description-->
            </p>
            <p class="description-copy">
              When shooting action sports you have to be patient. And, of course, be very fast when the perfect moment happens. To achieve the film the way you want, sometimes you have to shot a lot of scenes until you get the perfect ones to edit.
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
              Canon EOS 60D DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF 70-200mm f4, Canon EF 85mm f1.8 and Canon EF 10-22mm
            </p>

      </div>

      <img data="8" class="showcase-image" src="../img/showcase-moment-5.jpg" />
      
    </div>
    
    
  </div>

  <div id="moment-showcase" class="img-gallery-nav">

    <img id="arrowL" class="showcase-arrow-btn" src="../img/arrow-sm-left.png"/>
    <div id="dot-1" class="dot" data="1"><img src="../img/dot_sill.png"/></div>
    <div id="dot-2" class="dot" data="2"><img src="../img/dot_sill.png"/></div>
    <div id="dot-3" class="dot" data="3"><img src="../img/dot_sill.png"/></div>
    <div id="dot-4" class="dot" data="4"><img src="../img/dot_sill.png"/></div>
    <div id="dot-5" class="dot" data="5"><img src="../img/dot_sill.png"/></div>
    <img id="arrowR" class="showcase-arrow-btn" src="../img/arrow-sm-right.png"/>
  </div>


</div>

<a id="EOS-Rebel-T5i" href="http://shop.usa.canon.com/shop/en/catalog/canon-eos-t5i-digital-slr-camera?cm_mmc=Microsite-_-EOS-_-0518121-_-BringItT5i" target="_blank" class="main-prod">

  <img id="prod-3-cta" class="cta" src="../img/section-LearnMore.png" alt="Learn More"/>
  <img src="../img/section-product-3.jpg" alt="Canon Eos Rebel T5i"/>
</a>


<div class="section-dividers">
  <p class="hashtag">learn how to bring it</p>
</div>

<div class="learn-how">
   <div id="tutorial-wrapper" class="moment">
    <div class ="carousel-cover"></div>
   

    <div id="hide-right" class="tutorial-hide"></div>
    <div id="video-btn" class="tutorial-hide" data="moment">
      <img src="../img/play_btn.png"/>
    </div>
    <div id="hide-left" class="tutorial-hide"></div>
    
      <div id="tutorial-1" class="tuts"><img src="../img/section-moment-tutorial-1.jpg" /></div>    
      <div id="tutorial-2" class="tuts"><img src="../img/section-moment-tutorial-2.jpg" /></div>     
 
      <div id="tutorial-3" class="tuts"><img src="../img/section-moment-tutorial-3.jpg" /></div>
      
      <div id="tutorial-4" class="tuts"><img src="../img/section-moment-tutorial-4.jpg" /></div>
    


    
   </div> 

   <div id="moment-tutorials" class="tutorial-gallery-nav">
    <img id="arrowL" class="arrow-btn" src="../img/arrow-sm-left.png"/>
    <div id="dot-1" class="dot" data="1"><img src="../img/dot_sill.png"/></div>
    <div id="dot-2" class="dot" data="2"><img src="../img/dot_sill.png"/></div>
    <div id="dot-3" class="dot" data="3"><img src="../img/dot_sill.png"/></div>
    <div id="dot-4" class="dot" data="4"><img src="../img/dot_sill.png"/></div>
    <img id="arrowR" class="arrow-btn" src="../img/arrow-sm-right.png"/>
   </div>

</div>




