
<h2 class="page-header">with your family</h2>


<div class="page-hero">


  <div id="orchard" class="video-poster">
    <img src="../img/poster-orchard.jpg" alt="The Orchard"/>
  </div>

  <div class="video-description">

    <p class="title">
      The Orchard
    </p>
    <p class="director">
      a Rick Marrone film
    </p>
    <p class="body-copy">
      It doesn’t have to play in a theater to be a film. Now anyone can shoot Hollywood caliber Full HD Video on our Canon EOS DSLRs. Check out this movie trailer made with footage shot entirely by Rick, as well as some photographs he shot at the orchard. 
    </p>
    <a id="orchard-cta" href="javascript:void(0);" class="cta">How Rick shot his film</a>

  </div>

 


</div>

 <div id="family" class="page-hero-screens">
    <div>
      <img data="1" src="../img/orchard-still-1.jpg"/>
    </div>
    <div class="center-screen">
      <img data="2" src="../img/orchard-still-2.jpg"/>
    </div>
    <div>
        <img data="3" src="../img/orchard-still-3.jpg"/>
    </div>
  </div>




<div class="section-dividers">
  <p class="hashtag">#BRINGIT showcase</p>
</div>


<div id="family" class="showcase">

 

  <div class="img-gallery">
    <div class ="carousel-cover"></div>
    
    <div id="img-1" class="mages">

      <div class="description">
            <br/>
            <p class="title">
             submersion
            </p>
            <p class="photographer">
              Viktor Cap
            </p>


            <p class="sub-heads">
               <!--Description-->
            </p>
            <p class="description-copy">
              No artificial light was used on this shot. The key for shooting underwater, in my book, is buoyancy. I always try to stabilize the camera well enough to get an image with a sharp focal point. In this case, fast shutter speed was necessary to capture fast movement and the lovely bubbles without blur. 
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
              
              Canon EOS 5D Mark III DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF 35mm f/1.4L USM
            </p>

      </div>

      <img data="4" class="showcase-image" src="../img/showcase-family-1.jpg" />

    </div>

    <div id="img-2" class="mages">

      <div class="description">
            <br/>
            <p class="title">
              Summer Freedom
            </p>
            <p class="photographer">
              Charlie Round-Turner
            </p>


            <p class="sub-heads">
               <!--Description-->
            </p>
            <p class="description-copy">
              I took this photo using the auto-mode, because it was a quick grab shot. I only checked the viewfinder to make sure I was getting a fast enough shutter speed to catch the moving target. 
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
              Canon EOS 5D DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF 24-105mm f/4L IS USM
            </p>

      </div>

      <img data="5" class="showcase-image" src="../img/showcase-family-2.jpg" />
      
    </div>

    <div id="img-3" class="mages">


      <div class="description">
            <br/>
            <p class="title">
              Brothers 
            </p>
            <p class="photographer">
              Lisa Peardon 
            </p>


            <p class="sub-heads">
               <!--Description-->
            </p>
            <p class="description-copy">
              I was hanging out with my nephews on the dock of their grandparents’ house. I saw this cute scene and decided to take a picture. I shot it at high shutter speed so the sky wouldn’t blow out. And I also tried to keep the F/stop as high as possible, because this helps to keep the whole scene in focus. 
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
              Canon EOS 5D DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF 24-70mm f/2.8L II USM
            </p>

      </div>

      <img data="6" class="showcase-image" src="../img/showcase-family-3.jpg" />
      
    </div>
    
    <div id="img-4" class="mages">


      <div class="description">
            <br/>
            <p class="title">
              The Scream
            </p>
            <p class="photographer">
              Lisa Peardon 
            </p>


            <p class="sub-heads">
              <!--Description-->
            </p>
            <p class="description-copy">
              I used f/2.8 for shallow depth of field so as not to emphasize the background. This way his face really popped up. 
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
              Canon EOS 5D DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF 24-70mm f/2.8L II USM
            </p>

      </div>

      <img data="7" class="showcase-image" src="../img/showcase-family-4.jpg" />
      
    </div>

        <div id="img-5" class="mages">


      <div class="description">
            <br/>
            <p class="title">
              Liska, My Dog 
            </p>
            <p class="photographer">
              Linda Kohler 
            </p>


            <p class="sub-heads">
              <!--Description-->
            </p>
            <p class="description-copy">
              If there is enough available light, try to use the lowest ISO setting possible and try to lock it on the manual mode. Because if the ISO is set to auto, the value will be jumping around and you maybe have no constant illumination on your entire scene.
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
              Canon EOS 7D DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF 85mm f/1.8 USM
            </p>

      </div>

      <img data="8" class="showcase-image" src="../img/showcase-family-5.jpg" />
      
    </div>
  </div>

  <div id="family-showcase" class="img-gallery-nav">

    <img id="arrowL" class="showcase-arrow-btn" src="../img/arrow-sm-left.png"/>
    <div id="dot-1" class="dot" data="1"><img src="../img/dot_sill.png"/></div>
    <div id="dot-2" class="dot" data="2"><img src="../img/dot_sill.png"/></div>
    <div id="dot-3" class="dot" data="3"><img src="../img/dot_sill.png"/></div>
    <div id="dot-4" class="dot" data="4"><img src="../img/dot_sill.png"/></div>
    <div id="dot-5" class="dot" data="5"><img src="../img/dot_sill.png"/></div>
    <img id="arrowR" class="showcase-arrow-btn" src="../img/arrow-sm-right.png"/>
  </div>


</div>

<a id="EOS-Rebel-SL1" href="http://shop.usa.canon.com/shop/en/catalog/canon-eos-sl1-digital-slr-camera-landing-page?cm_mmc=Microsite-_-EOS-_-0518121-_-BringItSL1" target="_blank" class="main-prod">

  <img class="cta" src="../img/section-LearnMore.png" alt="Learn More"/>
  <img src="../img/section-product-1.jpg" alt="Canon Eos Rebel SL1"/>
</a>


<div class="section-dividers">
  <p class="hashtag">learn how to bring it</p>
</div>

<div class="learn-how">
   <div id="tutorial-wrapper" class="family">
    <div class ="carousel-cover"></div>
   

    <div id="hide-right" class="tutorial-hide"></div>
    <div id="video-btn" class="tutorial-hide" data="family">
      <img src="../img/play_btn.png"/>
    </div>
    <div id="hide-left" class="tutorial-hide"></div>
    
      <div id="tutorial-1" class="tuts"><img src="../img/section-family-tutorial-1.jpg" /></div>    
      <div id="tutorial-2" class="tuts"><img src="../img/section-family-tutorial-2.jpg" /></div>     
 
      <div id="tutorial-3" class="tuts"><img src="../img/section-family-tutorial-3.jpg" /></div>
      
      <div id="tutorial-4" class="tuts"><img src="../img/section-family-tutorial-4.jpg" /></div>
    
      <div id="tutorial-5" class="tuts"><img src="../img/section-family-tutorial-5.jpg" /></div>     

      <div id="tutorial-6" class="tuts"><img src="../img/section-family-tutorial-6.jpg" /></div>
      
      <div id="tutorial-7" class="tuts"><img src="../img/section-family-tutorial-7.jpg" /></div>


    
   </div> 

   <div id="family-tutorials" class="tutorial-gallery-nav">
    <img id="arrowL" class="arrow-btn" src="../img/arrow-sm-left.png"/>
    <div id="dot-1" class="dot" data="1"><img src="../img/dot_sill.png"/></div>
    <div id="dot-2" class="dot" data="2"><img src="../img/dot_sill.png"/></div>
    <div id="dot-3" class="dot" data="3"><img src="../img/dot_sill.png"/></div>
    <div id="dot-4" class="dot" data="4"><img src="../img/dot_sill.png"/></div>
    <div id="dot-5" class="dot" data="5"><img src="../img/dot_sill.png"/></div>
    <div id="dot-6" class="dot" data="6"><img src="../img/dot_sill.png"/></div>
    <div id="dot-7" class="dot" data="7"><img src="../img/dot_sill.png"/></div>
    <img id="arrowR" class="arrow-btn" src="../img/arrow-sm-right.png"/>
   </div>

</div>




