

<!--<div class="sep"></div>-->

 

<h2 class="leading">
  Bring your Canon. Bring your lenses. Bring your talent. Bring everything you’ve got. Then share your photographs and Full HD video with #bringit and show the world. Soon your creativity can be featured here and wherever we bring it next.

</h2>

<div id="header-video" class="video-holder">
	<img class="poster" src="img/headerPoster.jpg"/>
		
</div>



<div class="sep"></div>


<div class="categories">
	  <div id="cat-1" class="cats">
      
        <div class="label">with your family</div>
        <div class="ro"></div>
        <div class="btn">with your family</div>

    </div>

    <div id="cat-2" class="cats">
      <div class="label">when you travel</div>
      <div class="ro"></div>
      <div class="btn">when you travel</div>
    </div>

    <div id="cat-3" class="cats">
      <div class="label">in the moment</div>
      <div class="ro"></div>
      <div class="btn">in the moment</div>
    </div>
    
    
    
</div>

<div class="page-dividers">
  <p class="hashtag">#BRINGIT</p>
  <p>Check out these photographs and Full HD videos and show us how you #bringit</p>

</div>


<ul id="grid" class="grid-cols">
  <li id="photo1" data="1"><img src="/img/1.jpg"></li>
  <li id="photo35" data="35"><img src="/img/35.jpg"></li>
  <li id="photo4" data="4"><img src="/img/4.jpg"></li>
  <li id="p2"><a id="prod-2" href="http://shop.usa.canon.com/shop/en/catalog/eos-rebel-t5i-digital-slr-camera-nir-specials?cm_mmc=eStore-_-Site-_-0826128-_-BringItT5i" class="prod" target="_blank"><img class="cta" src="img/learnMore.png" alt="Learn More"/><img src="/img/prod_2.jpg"></a></li>
   <li id="photo11" data="11"><img src="/img/11.jpg"></li>
   <li id="photo14" data="14"><img src="/img/14.jpg"></li>
   <li id="photo16" data="16"><img src="/img/16.jpg"></li>
   <li id="photo23" data="23"><img src="/img/23.jpg"></li>
   <li id="p6"><a id="prod-6" href="http://usa.canon.com/pps" class="prod" target="_blank"><img class="cta" src="img/learnMore.png" alt="Learn More"/><img src="/img/prod_6.jpg"/></a></li>
   <li id="photo24" data="24"><img src="/img/24.jpg"></li>
   <li id="v4"><a href="javascript:void(0)" id="video4" class="vid"><img src="/img/video04.jpg"></a></li>
   <li id="photo29" data="29"><img src="/img/29.jpg"></li>
   <li id="photo32" data="32"><img src="/img/32.jpg"></li>
</ul>
<ul id="grid-mid" class="grid-cols">
   <li><a href="javascript:void(0)" id="video1" class="vid"><img class="narrow-li" src="/img/video01.jpg"></a></li>
  <li id="photo3" data="3"><img class="narrow-li" src="/img/3.jpg"></li>
 <li id="photo5" data="5"><img class="narrow-li" src="/img/5.jpg"></li>
 <li id="photo6" data="6"><img class="narrow-li" src="/img/6.jpg"></li>
 <li id="photo8" data="8"><img class="narrow-li" src="/img/8.jpg"></li>
<li id="photo9" data="9"><img class="narrow-li" src="/img/9.jpg"></li>
<li id="photo12" data="12"><img class="narrow-li" src="/img/12.jpg"></li>
<li id="photo15" data="15"><img class="narrow-li" src="/img/15.jpg"></li>
<li id="photo17" data="17"><img class="narrow-li" src="/img/17.jpg"></li>
<li id="photo18" data="18"><img class="narrow-li" src="/img/18.jpg"></li>
 <li id="photo20" data="20"><img class="narrow-li" src="/img/20.jpg"></li>
  <li id="photo26" data="26"><img class="narrow-li" src="/img/26.jpg"></li>
  <li id="photo22" data="22"><img class="narrow-li" src="/img/22.jpg"></li> 
  <li id="photo25" data="25"><img class="narrow-li" src="/img/25.jpg"></li>
  <li id="photo34" data="34"><img class="narrow-li" src="/img/34.jpg"></li>
  <li id="photo28" data="28"><img class="narrow-li" src="/img/28.jpg"></li>
   <li id="photo30" data="30"><img class="narrow-li" src="/img/30.jpg"></li>
   <li id="photo33" data="33"><img class="narrow-li" src="/img/33.jpg"></li>
   <li id="photo36" data="36"><img class="narrow-li" src="/img/36.jpg"></li>
</ul>

<ul id="grid" class="grid-cols">
  <li id="photo2" data="2"><img src="/img/2.jpg"></li>
<li><a id="prod-1" href="http://shop.usa.canon.com/shop/en/catalog/eos-70d-digital-slr-camera-nir-specials?cm_mmc=eStore-_-Site-_-0826128-_-BringIt70D" target="_blank" class="prod"><img class="cta" src="img/learnMore.png" alt="Learn More"/><img src="/img/prod_1.jpg"></a></li>
<li id="photo7" data="7"><img src="/img/7.jpg"></li>
<li id="photo10" data="10"><img src="/img/10.jpg"></li>
<li><a href="javascript:void(0)" id="video3" class="vid"><img src="/img/video03.jpg"></a></li>
 <li><a id="prod-3" href="http://shop.usa.canon.com/shop/en/catalog/eos-rebel-sl1-digital-slr-camera-nir-specials?cm_mmc=eStore-_-Site-_-0826128-_-BringItSL1" target="_blank" class="prod"><img class="cta" src="img/learnMore.png" alt="Learn More"/><img src="/img/prod_3.jpg"></a></li>
 <li id="photo19" data="19"><img src="/img/19.jpg"></li>
 <li id="photo37" data="37"><img src="/img/37.jpg"/></li>
 <li id="photo13" data="13"><img src="/img/13.jpg"></li>
 <li id="photo27" data="27"><img src="/img/27.jpg"></li>
 <li id="photo31" data="31"><img src="/img/31.jpg"></li>
  <li><a id="prod-5" href="http://shop.usa.canon.com/shop/en/catalog/cameras?cm_mmc=Microsite-_-EOS-_-0518121-_-BringItDirect" class="prod" target="_blank"><img class="cta" src="img/learnMore.png" alt="Learn More"/><img src="/img/prod_5.jpg"></a></li>

  
</ul>









