
<h2 class="page-header">when you travel</h2>


<div class="page-hero">


  <div id="vacation" class="video-poster">
    <img src="../img/poster-vacation.jpg" alt="Our Vacation"/>
  </div>

  <div class="video-description">

    <p class="title">
      our vacation
    </p>
    <p class="director">
      a Dana Saint Film
    </p>
    <p class="body-copy">
      It doesn’t have to play in a theater to be a film. Now anyone can shoot Hollywood caliber Full HD Video on our Canon EOS DSLRs. Check out this movie trailer made with footage shot entirely by Dana, as well as some photographs he shot on his vacation.
    </p>
    <a id="vacation-cta" href="#" class="cta">How dana shot his film</a>

  </div>

 


</div>

 <div id="travel" class="page-hero-screens">
    <div>
      <img data="1" src="../img/vacation-still-1.jpg"/>
    </div>
    <div class="center-screen">
      <img data="2" src="../img/vacation-still-2.jpg"/>
    </div>
    <div>
        <img data="3" src="../img/vacation-still-3.jpg"/>
    </div>
  </div>




<div class="section-dividers">
  <p class="hashtag">#BRINGIT showcase</p>
</div>


<div id="travel" class="showcase">

 

  <div class="img-gallery">
    <div class ="carousel-cover"></div>
    
    <div id="img-1" class="mages">

      <div class="description">
        <br/>
            <p class="title">
              Footsteps in the beach
            </p>
            <p class="photographer">
              Xhani Xhori 
              <!-- Luke Gerspm | Australia -->
            </p>


            <p class="sub-heads">
              <!--Description-->
            </p>
            <p class="description-copy">
              To get this shot with these colors, I used a graduated filter to balance the light of the sky. After a man walked towards the dry land and left the footsteps, I had to be very quick in adjusting my shutter speed to avoid the waves erasing them. 
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
             Canon EOS 5D Mark II DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF 16-35mm f/2.8L II USM
            </p>

      </div>

      <img data="4" class="showcase-image" class="showcase-image" src="../img/showcase-travel-1.jpg" />

    </div>

    <div id="img-2" class="mages">

      <div class="description">
            <br/>
            <p class="title">
              adrift, Mentawai Islands, Indonesia
            </p>
            <p class="photographer">
              Luke Gerson
            </p>


            <p class="sub-heads">
               <!--Description-->
            </p>
            <p class="description-copy">
              The bright midday sun isn't the best for landscape images, but for water-based photos it can light the ocean perfectly. It also allows you to shoot fast enough to freeze the water with sufficient depth of field and at a low ISO, which guarantees better image quality. To capture this image we used an underwater housing device with a dome port. The dome port is essential in capturing over/under split shot photographs.
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
              Canon EOS 7D DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF 8-15mm f/4L Fisheye USM
            </p>

      </div>

      <img data="5" class="showcase-image" src="../img/showcase-travel-2.jpg" />
      
    </div>

    <div id="img-3" class="mages">


      <div class="description">
            <br/>
            <p class="title">
              New eve
            </p>
            <p class="photographer">
              Yves Rubin
            </p>


            <p class="sub-heads">
               <!--Description-->
            </p>
            <p class="description-copy">
              This was one of those moments when I had to stop while driving back from Italy towards the west of Switzerland. To achieve this shot, I combined two different exposures to separate the sky from the background so that the exposure latitude would represent best what I saw. Natural colors were enhanced slightly, but the overall shot is close to what I was contemplating on that beautiful evening.
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
              Canon EOS 1Ds Mark II DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF 24-105mm f/4L IS USM
            </p>

      </div>

      <img data="6" class="showcase-image" src="../img/showcase-travel-3.jpg" />
      
    </div>

    <div id="img-4" class="mages">


      <div class="description">
            <br/>
            <p class="title">
             Washingday Burano Venice Italy
            </p>
            <p class="photographer">
              Knud Nielsen 
            </p>


            <p class="sub-heads">
               <!--Description-->
            </p>
            <p class="description-copy">
              I captured this shot during a visit to Venice and the islands around in the lagoon. When I’m travelling and shooting, I always try to wake up very early in the morning to get the perfect light. 
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
              Canon EOS 5D DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF 24-105mm f/4L IS USM
            </p>

      </div>

      <img data="7" class="showcase-image" src="../img/showcase-travel-4.jpg" />
      
    </div>

    <div id="img-5" class="mages">


      <div class="description">
            <br/>
            <p class="title">
             Landscapes
            </p>
            <p class="photographer">
              Henry Jun Wah Lee 
            </p>


            <p class="sub-heads">
               <!--Description-->
            </p>
            <p class="description-copy">
              For daytime shots, if the light is stable, shooting on manual mode is always a good idea. However if the light is dynamic and changing, such as during a sunrise or sunset, consider shooting with aperture priority. It will make your life easier.
            </p>


            <p class="sub-heads">
              camera
            </p>
            <p class="camera-copy">
              Canon 5D Mark II DSLR and Canon 5D Mark III DSLR
            </p>


            <p class="sub-heads">
              lens
            </p>
            <p class="lens-copy">
              Canon EF 16-35mm f/2.8 and Canon EF 24-70mm f/2.8
            </p>

      </div>

      <img data="8" class="showcase-image" src="../img/showcase-travel-5.jpg" />
      
    </div>

    
    
  </div>



  <div id="travel-showcase" class="img-gallery-nav">
    <img id="arrowL" class="showcase-arrow-btn" src="../img/arrow-sm-left.png"/>
    <div id="dot-1" class="dot" data="1"><img src="../img/dot_sill.png"/></div>
    <div id="dot-2" class="dot" data="2"><img src="../img/dot_sill.png"/></div>
    <div id="dot-3" class="dot" data="3"><img src="../img/dot_sill.png"/></div>
    <div id="dot-4" class="dot" data="4"><img src="../img/dot_sill.png"/></div>
    <div id="dot-5" class="dot" data="5"><img src="../img/dot_sill.png"/></div>
    <img id="arrowR" class="showcase-arrow-btn" src="../img/arrow-sm-right.png"/>
  </div>


</div>

<a id="EOS-70D" href="http://shop.usa.canon.com/shop/en/catalog/canon-eos-70d-digital-slr-camera-landing-page?cm_mmc=Microsite-_-EOS-_-0518121-_-BringIt70D" target="_blank" class="main-prod">

  <img id="prod-2-cta" class="cta" src="../img/section-LearnMore.png" alt="Learn More"/>
  <img src="../img/section-product-2.jpg" alt="Canon Eos 70D"/>
</a>


<div class="section-dividers">
  <p class="hashtag">learn how to bring it</p>
</div>

<div class="learn-how">
   <div id="tutorial-wrapper" class="travel">
    <div class ="carousel-cover"></div>
   

    <div id="hide-right" class="tutorial-hide"></div>
    <div id="video-btn" class="tutorial-hide" data="travel">
      <img src="../img/play_btn.png"/>
    </div>
    <div id="hide-left" class="tutorial-hide"></div>
    
      <div id="tutorial-1" class="tuts"><img src="../img/section-travel-tutorial-1.jpg" /></div>    
      <div id="tutorial-2" class="tuts"><img src="../img/section-travel-tutorial-2.jpg" /></div>     
 
      <div id="tutorial-3" class="tuts"><img src="../img/section-travel-tutorial-3.jpg" /></div>
      
      <div id="tutorial-4" class="tuts"><img src="../img/section-travel-tutorial-4.jpg" /></div>

      <div id="tutorial-5" class="tuts"><img src="../img/section-travel-tutorial-5.jpg" /></div>
      <div id="tutorial-6" class="tuts"><img src="../img/section-travel-tutorial-6.jpg" /></div>
      <div id="tutorial-7" class="tuts"><img src="../img/section-travel-tutorial-7.jpg" /></div>
      <div id="tutorial-8" class="tuts"><img src="../img/section-travel-tutorial-8.jpg" /></div>
      <div id="tutorial-9" class="tuts"><img src="../img/section-travel-tutorial-9.jpg" /></div>
    


    
   </div> 

   <div id="travel-tutorials" class="tutorial-gallery-nav">
    <img id="arrowL" class="arrow-btn" src="../img/arrow-sm-left.png"/>
    <div id="dot-1" class="dot" data="1"><img src="../img/dot_sill.png"/></div>
    <div id="dot-2" class="dot" data="2"><img src="../img/dot_sill.png"/></div>
    <div id="dot-3" class="dot" data="3"><img src="../img/dot_sill.png"/></div>
    <div id="dot-4" class="dot" data="4"><img src="../img/dot_sill.png"/></div>
    <div id="dot-5" class="dot" data="5"><img src="../img/dot_sill.png"/></div>
    <div id="dot-6" class="dot" data="6"><img src="../img/dot_sill.png"/></div>
    <div id="dot-7" class="dot" data="7"><img src="../img/dot_sill.png"/></div>
    <div id="dot-8" class="dot" data="8"><img src="../img/dot_sill.png"/></div>
    <div id="dot-9" class="dot" data="9"><img src="../img/dot_sill.png"/></div>
    <img id="arrowR" class="arrow-btn" src="../img/arrow-sm-right.png"/>
   </div>

</div>




